android {
    defaultConfig { testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner' }
    sourceSets.androidTest.assets.srcDir 'schemas'
}
dependencies {
    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test:core:1.7.0'
    androidTestImplementation 'androidx.room:room-testing-android:2.8.4'
}
